-- Sequence creation
CREATE SEQUENCE bloc_seq
   START WITH 1
   INCREMENT BY 1
   NOCACHE
   NOCYCLE;

-- Function to retrieve the next value
CREATE OR REPLACE FUNCTION GET_BLOC_SEQ
   RETURN NUMBER
IS
   retour NUMBER;
BEGIN
   SELECT bloc_seq.NEXTVAL INTO retour FROM DUAL;
   RETURN retour;
END;
/


CREATE SEQUENCE dim_seq START WITH 1 INCREMENT by 1 NOCACHE NOCYCLE;
CREATE OR REPLACE FUNCTION GET_DIMUS_SEQ
   RETURN NUMBER
IS
   retour NUMBER;
BEGIN
   SELECT dim_seq.NEXTVAL INTO retour FROM DUAL;
   RETURN retour;
END;
/


CREATE SEQUENCE trans_seq START WITH 1 INCREMENT by 1;
CREATE OR REPLACE Function GET_TRANS_SEQ
   RETURN NUMBER
IS
   retour NUMBER;
BEGIN
   SELECT trans_seq.NEXTVAL into retour FROM DUAL;
   RETURN retour; 
END;
/


CREATE SEQUENCE transf_seq START WITH 1 INCREMENT by 1;
CREATE OR REPLACE Function GET_TRANSF_SEQ
   RETURN NUMBER
IS
   retour NUMBER;
BEGIN
   SELECT transf_seq.NEXTVAL into retour FROM DUAL;
   RETURN retour; 
END;
/
